steps:
# constuire image Docker
- name: 'gcr.io/cloud-builders/docker'
  args: 
    - 'build'
    - '-t'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/website-tools/wordpress-custom:${_COMMIT_SHA}'
    - '.'

#  push Docker vers Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: 
    - 'push'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/website-tools/wordpress-custom:${_COMMIT_SHA}'
substitutions:
  _COMMIT_SHA: 'latest'

